#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

#if $(ynh_compare_current_package_version --comparison le --version "18.12.17~ynh1")
#then
	# Purge old root directory's contents
	#ynh_script_progression --message="Removing old files..."
	#mkdir /tmp/ofbiz
	#chmod -R o-rwx /tmp/ofbiz
	#chown -R $app:www-data /tmp/ofbiz
	#mv -f $install_dir/* $install_dir/.[!.]* /tmp/ofbiz
	#mv /tmp/ofbiz $install_dir/
#fi

ynh_setup_source --dest_dir="$install_dir/build"

env_string=" "
jh_string=" "

if [ $(lsb_release --codename --short) == 'bookworm' ]
then
    ynh_setup_source --dest_dir="$install_dir/jdk" --source_id="jdk"
    env_string="env PATH=$install_dir/jdk/bin:$PATH JAVA_HOME=$install_dir/jdk"
    jh_string="Environment=JAVA_HOME=\"$install_dir/jdk\""
fi

chown -R "$app:www-data" "$install_dir/build"

#=================================================
# CREATE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression --message="Configuring a PostgreSQL database..."

ynh_psql_execute_as_root --sql="CREATE DATABASE ${db_name}olap WITH OWNER ${db_user} TEMPLATE template0 ENCODING 'UTF8';"
ynh_psql_execute_as_root --sql="CREATE DATABASE ${db_name}tenant WITH OWNER ${db_user} TEMPLATE template0 ENCODING 'UTF8';"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression --message="Building app..."

_fixup_config

pushd "$install_dir/build"
    ynh_exec_as "$app" $env_string ./gradle/init-gradle-wrapper.sh
    ynh_exec_as "$app" $env_string ./gradlew --no-daemon jar
    ynh_secure_remove --file="$install_dir/build/framework/entity/lib"
    ynh_setup_source --source_id="pgjdbc" --dest_dir="$install_dir/build/framework/entity/lib"
    chown -R $app:$app "$install_dir/build/framework/entity/lib"
    ynh_exec_as "$app" $env_string ./gradlew --no-daemon distTar
popd

ynh_exec_as "$app" tar xf $install_dir/build/build/distributions/ofbiz.tar -C $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
_ci_fix_nginx
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config
yunohost service add "$app" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..."

ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log" --line_match="is started and ready" --timeout=600

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
