#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

if ynh_exec_warn_less yunohost service status "$app" >/dev/null; then
    ynh_script_progression --message="Removing $app service integration..."
    ynh_systemd_action --service_name="$app" --action="stop" --log_path="/var/log/$app/$app.log" --line_match="Stopped container component-container"
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config

# Remove the dedicated NGINX config
ynh_remove_nginx_config

ynh_remove_logrotate

# Remove the log files

# Remove additional databases
ynh_psql_drop_db "${db_name}tenant"
ynh_psql_drop_db "${db_name}olap"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
