#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd" --wait_until="Stopped container component-container"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Remove legacy admin key
if [ -n "${admin:-}" ]; then
    ynh_app_setting_delete --key=admin
fi

if $(ynh_app_upgrading_from_version_before_or_equal_to 18.12.17~ynh1)
then
    # Purge old root directory's contents
    ynh_script_progression "Moving old files..."
    mkdir /tmp/ofbiz
    chmod -R o-rwx /tmp/ofbiz
    chown -R $app:www-data /tmp/ofbiz
    mv -f $install_dir/* $install_dir/.[!.]* /tmp/ofbiz
    mv /tmp/ofbiz $install_dir/
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/build"

env_string=" "
jh_string=" "

if [ $(lsb_release --codename --short) == 'bookworm' ]
then
    ynh_setup_source --dest_dir="$install_dir/jdk" --source_id="jdk" --full_replace
    env_string="env PATH=$install_dir/jdk/bin:$PATH JAVA_HOME=$install_dir/jdk"
    jh_string="Environment=JAVA_HOME=\"$install_dir/jdk\""
fi

chown -R "$app:www-data" "$install_dir/build"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

_fixup_config

pushd "$install_dir/build"
    ynh_exec_as_app $env_string ./gradle/init-gradle-wrapper.sh
    ynh_exec_as_app $env_string ./gradlew --no-daemon jar 2>&1
    ynh_safe_rm "$install_dir/build/framework/entity/lib"
    ynh_setup_source --source_id="pgjdbc" --dest_dir="$install_dir/build/framework/entity/lib"
    chown -R $app:$app "$install_dir/build/framework/entity/lib"
    ynh_exec_as_app $env_string ./gradlew --no-daemon distTar 2>&1
popd

ynh_exec_as_app tar xf $install_dir/build/build/distributions/ofbiz.tar -C $install_dir
ynh_safe_rm "$install_dir/build"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
_ci_fix_nginx
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"  --wait_until="is started and ready"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
